/**
 * Excel sheet enumeration + sheet → CSV conversion.
 * Uses an in-memory .xlsx generated by SheetJS itself.
 */
import { describe, it, expect } from 'vitest';
import { parseExcelSheets, excelSheetToCsv } from '../../duckdb/excel';

async function makeXlsxFile(sheets: Record<string, unknown[][]>): Promise<File> {
  const XLSX = await import('xlsx');
  const wb = XLSX.utils.book_new();
  for (const [name, rows] of Object.entries(sheets)) {
    const ws = XLSX.utils.aoa_to_sheet(rows);
    XLSX.utils.book_append_sheet(wb, ws, name);
  }
  const buf = XLSX.write(wb, { type: 'array', bookType: 'xlsx' });
  return new File([buf], 'test.xlsx', {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  });
}

describe('parseExcelSheets', () => {
  it('enumerates sheets and their row counts', async () => {
    const file = await makeXlsxFile({
      Sheet1: [
        ['a', 'b'],
        [1, 2],
        [3, 4],
      ],
      Sheet2: [['x'], [10], [20], [30], [40]],
    });
    const { sheets } = await parseExcelSheets(file);
    expect(sheets).toHaveLength(2);
    expect(sheets[0]?.name).toBe('Sheet1');
    expect(sheets[0]?.rowCount).toBe(2);
    expect(sheets[1]?.name).toBe('Sheet2');
    expect(sheets[1]?.rowCount).toBe(4);
  });

  it('returns rowCount=0 for empty sheets', async () => {
    const file = await makeXlsxFile({ Empty: [] });
    const { sheets } = await parseExcelSheets(file);
    expect(sheets[0]?.rowCount).toBe(0);
  });
});

describe('excelSheetToCsv', () => {
  it('converts a sheet to a CSV file with the original name + sheet', async () => {
    const file = await makeXlsxFile({
      People: [
        ['name', 'age'],
        ['Alice', 30],
        ['Bob', 25],
      ],
    });
    const csv = await excelSheetToCsv(file, 'People');
    expect(csv.name).toBe('test__People.csv');
    expect(csv.type).toBe('text/csv');
    const text = await csv.text();
    expect(text).toContain('name,age');
    expect(text).toContain('Alice,30');
    expect(text).toContain('Bob,25');
  });

  it('throws when the sheet does not exist', async () => {
    const file = await makeXlsxFile({ Foo: [['x']] });
    await expect(excelSheetToCsv(file, 'Bar')).rejects.toThrow(/Sheet "Bar" not found/);
  });

  it('sanitizes unsafe sheet names in the output filename', async () => {
    const file = await makeXlsxFile({ 'weird name!': [['x']] });
    const csv = await excelSheetToCsv(file, 'weird name!');
    expect(csv.name).toMatch(/test__weird_name_\.csv$/);
  });
});
